<main>
  <header><a class="brand" href="/">JotDB</a><nav><a href="#examples">Examples</a><a href="#benchmarks">Benchmarks</a><a href="#why">Why</a><a href="https://github.com/acoyfellow/JotDB">GitHub →</a></nav></header>
  <section class="hero">
    <div class="hero-glow"></div><p class="eyebrow">a Cloudflare Durable Object database</p><h1>A simple durable database for Cloudflare apps.</h1><p class="lead">JotDB gives you one typed, validated Durable Object per user, tenant, room, session, or actor — without SQL, migration files, ORMs, or connection strings.</p><div class="actions"><a class="primary" href="https://github.com/acoyfellow/JotDB">Try JotDB →</a><a class="secondary" href="#examples">See examples</a></div><div class="hero-proof"><strong>No migrations.</strong><span>Schema validation built in.</span><span>One Durable Object per entity.</span></div>
  </section>
  <section id="examples"><h2>Three common app shapes. One simple API.</h2><article class="hero-code"><p>Preferences, feature flags, and chat history all become one Durable Object per entity.</p><pre><code><span class="kw">const</span> prefs = env.JOTDB.<span class="fn">getByName</span>(<span class="str">"user:42"</span>)
<span class="kw">await</span> prefs.<span class="fn">setAll</span>(&#123; theme: <span class="str">"dark"</span>, notifications: <span class="bool">true</span> &#125;)

<span class="kw">const</span> flags = env.JOTDB.<span class="fn">getByName</span>(<span class="str">"tenant:acme"</span>)
<span class="kw">await</span> flags.<span class="fn">set</span>(<span class="str">"aiSearch"</span>, <span class="bool">true</span>)

<span class="kw">const</span> room = env.JOTDB.<span class="fn">getByName</span>(<span class="str">"room:general"</span>)
<span class="kw">await</span> room.<span class="fn">push</span>(&#123; body: <span class="str">"hello"</span> &#125;)</code></pre></article></section>
  <section id="benchmarks"><h2>Built for the flows your app actually has.</h2><p class="section-lead">We tested the kinds of state people actually ship: preferences, feature flags, chat rooms, sessions, and lots of small isolated objects.</p><div class="grid metric-grid"><article><span>Preferences</span><strong>100 writes</strong><p>One user updating one small object. No migration step. No table lookup ceremony.</p></article><article><span>Feature flags</span><strong>1,000 reads</strong><p>One tenant reading one flag object. Fast to understand, easy to keep isolated.</p></article><article><span>Chat history</span><strong>20 appends</strong><p>One room adding messages to one durable stream of state.</p></article></div><div class="flow"><div><span>Traditional database flow</span><strong>schema → migration → query → join → update</strong></div><div><span>JotDB flow</span><strong>object → validate → write</strong></div></div><a class="text-link" href="https://github.com/acoyfellow/JotDB#benchmarking">See the raw benchmark modes and test suite →</a></section>
  <section id="why"><h2>Why JotDB</h2><div class="grid"><article><h3>No migrations</h3><p>Add fields with code, not migration files. Keep iteration fast while your product is still moving.</p></article><article><h3>Validation at the edge</h3><p>Schema checks happen where the state lives, before malformed data spreads through your app.</p></article><article><h3>Actor-style isolation</h3><p>Each entity gets its own Durable Object boundary and strong consistency model.</p></article></div><div class="compare"><div><span>D1</span><strong>Tables, SQL, migrations, joins</strong></div><div><span>JotDB</span><strong>Objects, validation, no migration workflow</strong></div></div></section>
  <footer>Use JotDB for bounded per-entity state. Use D1 for joins, reporting, and relational queries.</footer>
</main>
